Port: 80 # Web traffic ingress

Logging:
  LogLevel:
    Default: Debug
    Microsoft: Warning # Reduce ASP.NET Core verbosity
  Format: Plain

Policies:
  StartupRetries:
    - 00:00:15
    - 00:00:30

Database:
  ConnectionString: Data Source=myservice.db

Identity:
  #Authority: http://identity-myinstance.local.myaxoom.eu
  ClientSecret: myvendor-myapp-identity-client-secret
  ApiName: myvendor-myapp.api
  ApiSecret: myvendor-myapp-identity-api-secret
  RequireHttpsMetadata: false
