helmDefaults:
  force: true # Allow deploying over failed releases
  wait: true # Wait for all Pods to become ready

# Registers repos for use in requirements.yaml
repositories:
  - name: axoom-github
    url: https://axoom.github.io/charts/

# Installs charts
releases:
  - name: myvendor-myapp
    namespace: myteam
    chart: ./charts/myvendor-myapp

    values:
      - app:
          image:
            tag: '{{ requiredEnv "GitVersion_NuGetVersion" }}'
          ingress:
            enabled: true
            domain: 'myvendor-myapp.{{ requiredEnv "PUBLIC_CLUSTER_DOMAIN" }}'
          env:
            ASPNETCORE_ENVIRONMENT: '{{ env "ASPNETCORE_ENVIRONMENT" | default "Production" }}'
            Authentication__Authority: 'https://account.{{ requiredEnv "PUBLIC_CLUSTER_DOMAIN" }}'
            Authentication__ApiSecret: '{{ randAlphaNum 16 }}'
