# Specifies additional dependencies and exposes ports for local development/testing.
version: '3.4'

services:
  myvendor-myapp:
    ports:
      - "12345:80" # Keep in sync with ../deploy/local.docker-compose.override.yml
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      #IDENTITY_SERVER_URI: 'http://identity-myinstance.local.myaxoom.eu'
