# Specifies additional dependencies and exposes ports for local development/testing.
version: '3'

services:
  axoom-myapp:
    image: axoom-myapp
    ports:
      - "12345:80" # Keep in sync with ../deploy/local.docker-compose.override.yml
    environment:
      ASPNETCORE_ENVIRONMENT: Development
