# Builds and runs the services themselves. External dependencies, exposed ports, etc. are configured in docker-compose.override.yml.
version: '3.4'

services:
  myvendor-myapp:
    image: eu.gcr.io/axoom-image/myteam/myvendor-myapp:${VERSION-0.1-dev}
    build:
      context: ./App
      dockerfile: Dockerfile
