# Specifies additional dependencies and exposes ports for local development/testing.
version: '3'

services:
  axoom-myapp:
    image: axoom-myapp
    labels:
      traefik.frontend.rule: Host:axoom-myapp.vcap.me
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PORTAL_BASE_URI: http://vcap.me
      IDENTITY_SERVER_URI: http://identity.vcap.me
    links:
      - identity:identity.vcap.me # required because *.vcap.me resolves to 127.0.0.1, which would stay within the container

  # Portal + Identity Server

  traefik:
    image: traefik
    command: --web --docker
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portal:
    image: docker.axoom.cloud/services/portal
    labels:
      traefik.frontend.rule: Host:vcap.me
    environment:
      PORTAL_BASE_URI: http://vcap.me
      PORTAL_SERVICE_URI: http://portalservice.vcap.me
      IDENTITY_SERVER_URI: http://identity.vcap.me

  portalservice:
    image: docker.axoom.cloud/services/portalservice
    links:
      - identity:identity.vcap.me # required because *.vcap.me resolves to 127.0.0.1, which would stay within the container
    labels:
      traefik.frontend.rule: Host:portalservice.vcap.me
    environment:
      ALLOWED_ORIGINS: http://vcap.me
      APPS: '{
        "AppId": "axoom-myapp",
        "Version": "alpha",
        "DisplayName": {
            "en": "My App",
            "de": "My App"
        },
        "Description": {
          "en": "my description",
          "de": "my description"
        },
        "NavigationEntries": [{
            "LinkText": {
                "en": "My App",
                "de": "My App"
            },
            "TargetUrl": "http://axoom-myapp.vcap.me",
            "Category": "service",
            "Icon": {
                "Url_512x512px": "http://axoom-myapp.vcap.me/img/axoom-myapp.svg",
                "Url_32x32px": "http://axoom-myapp.vcap.me/img/axoom-myapp.svg"
            }
        }],
        "Support": "apps@axoom.com",
        "Website": "www.axoom.com"
      }'
      ASPNETCORE_ENVIRONMENT: Production

  identity:
    image: docker.axoom.cloud/services/identity
    labels:
      traefik.frontend.rule: Host:identity.vcap.me
    environment:
      INITIAL_USER: '{"userName":"dev","password":"Password12","email":"dev@axoom.com","firstName":"Dev","lastName":"SuperAdmin","company":"AXOOM GmbH","userLanguage":"en"}'
      connection_string: Server=identity_database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;Integrated
        Security=true;Pooling=true;
      CLIENTS: '{
                  "ClientId": "axoom-connectioncenter",
                  "ClientName": "Connection Center",
                  "RequireConsent": false,
                  "AllowedGrantTypes": [
                    "implicit"
                  ],
                  "AllowAccessTokensViaBrowser": true,
                  "RedirectUris": [
                    "http://axoom-myapp.vcap.me",
                    "http://axoom-myapp.vcap.me/#!/Login",
                    "http://axoom-myapp.vcap.me/#!/Login/",
                    "http://axoom-myapp.vcap.me/silentRenew.html"
                  ],
                  "AllowedScopes": [
                    "openid",
                    "profile",
                    "email",
                    "axoom-connectioncenter.api"
                  ],
                  "AllowedCorsOrigins": [
                    "http://axoom-myapp.vcap.me"
                  ]
            },{
            "ClientId": "AXOOM",
            "ClientName": "MyAXOOM Portal Web",
            "RequireConsent": false,
            "AllowedGrantTypes": [
              "implicit"
            ],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": [
              "http://vcap.me"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "axoom-identityserver.users",
              "axoom-portalservice.apps"
            ],
            "PostLogoutRedirectUris": [
              "http://vcap.me"
            ],
            "AllowedCorsOrigins": [
              "http://vcap.me"
            ]
          },{
            "ClientId": "Swagger",
            "ClientSecret": "Secret",
            "ClientName": "Swagger",
            "RequireConsent": false,
            "AccessTokenType": "Jwt",
            "AllowedGrantTypes": [
              "implicit"
            ],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": [
              "http://axoom-myapp.vcap.me/swagger/o2c.html"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "axoom-connectioncenter.api"
            ],
            "PostLogoutRedirectUris": [
              "http://axoom-myapp.vcap.me/"
            ],
            "AllowedCorsOrigins": [
              "http://axoom-myapp.vcap.me/"
            ]
          }'
      API_RESOURCES: '{
            "name":"axoom-connectioncenter.api",
            "apiSecrets":["e4143ff6-d7b9-4333-8070-57d49ec5acaa"],
            "scopes":[{"name":"axoom-connectioncenter.api", "claimTypes":["axoom-connectioncenter.api.role"]}]
          }'
      PERMISSIONS: '{
          "appId":"axoom-connectioncenter",
          "claimType":"axoom-connectioncenter.api.role",
          "claimValue":"User",
          "displayNames":{"en":"A User can only read the data.","de":"Als User darf man lesend auf Daten zugreifen."},
          "displayValues":{"en":"User","de":"Benutzer"},
          "descriptions":{"en":"Display Machine, Customers e.g.","de":"Z.B. Machinen, Kunden anzeigen"}
        },
        {
          "appId":"axoom-connectioncenter",
          "claimType":"axoom-connectioncenter.api.role",
          "claimValue":"Admin",
          "displayNames":{"en":"Admin has write access","de":"Administratoren k\u00f6nnen Dateien schreibend bearbeiten."},
          "displayValues":{"en":"Admin","de":"Administrator"},
          "descriptions":{"en":"Buy Licenses and stuff. Delete stuff","de":"Lizenzen kaufen und Dinge l\u00f6schen."}
        }'

  identity_database:
    image: postgres:9.6.2
    volumes:
      - identity_database:/var/lib/postgresql/data:rw

volumes:
  identity_database: {}
