# Builds and runs the services themselves. External dependencies, exposed ports, etc. are configured in docker-compose.override.yml.
version: '3'

services:
  myvendorname-myappname:
    image: ${DOCKER_REGISTRY-docker-ci.axoom.cloud}/apps/myvendorname-myappname:${VERSION-0.1-pre}
    build:
      context: ./App
      dockerfile: Dockerfile
