# Specifies additional dependencies and exposes ports for local development/testing.
version: '3'

services:
  myvendorname-myappname:
    image: myvendorname-myappname
    ports:
      - "12345:80" # Keep in sync with ../deploy/local.docker-compose.override.yml
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      #IDENTITY_SERVER_URI: 'http://identity-myinstance.local.myaxoom.eu'
